### ISSUE TITLE
Write Cluster Token to Vault

### ISSUE THREAD

**Issue by srueg** [projectsyn/lieutenant-operator#33]
The operator should store the cluster service account token in Vault automatically.

## Task Deliverables

- [ ] Service account token of clusters are stored in vault
- [ ] The tokens are stored under `kv/$TENANT_ID/$CLUSTER_ID/steward token=$CLUSTER_TOKEN`

**Comment by Kidswiss** [comment]
As discussed in the SYN meeting: I'll explore the possibilities of k8s token auth.

**Comment by Kidswiss** [comment]
Implemented Vault connection, tested with local Vault and unit tests.

left to do:

- [ ] test on synfra cluster with k8s authentication

**Comment by srueg** [comment]
We configured Vault with the following policy:
```hcl
path "kv/data/*" {
  capabilities = ["read", "create", "update"]
}
```

```console
vault policy write lieutenant-operator policy.hcl
```

And the following role for the Kubernetes Auth provider:

```console
vault write auth/kubernetes/role/lieutenant-operator bound_service_account_namespaces=lieutenant-prod,lieutenant-dev bound_service_account_names="lieutenant-operator" policies=lieutenant-operator ttl=1h token_max_ttl=12h
```

**Comment by srueg** [comment]
Maybe worth giving a try: https://pkg.go.dev/github.com/banzaicloud/bank-vaults/pkg/sdk@v0.3.0/vault?tab=doc

**Comment by srueg** [comment]
To follow up our discussion regarding ServiceAccount token rotation:

You can add a new token by creating a (empty) secret: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#to-create-additional-api-tokens
The controller will then add a token to the secret.

Unfortunately it seems that the `secrets` array of the ServiceAccount is not updated with this new secret.

**Comment by Kidswiss** [comment]
I can get all secrets, sort by newest creation date, iteraterate and get the newest one that matches the `kubernetes.io/service-account.name` to the cluster service account.

**Comment by srueg** [comment]
Yes, that's pretty much how `kubectl describe serviceaccount <name>` works: https://github.com/kubernetes/kubectl/blob/master/pkg/describe/describe.go#L2771

**Comment by Kidswiss** [comment]
Implemented all the todos we discussed yesterday (except the gitrepo thing).
